image: fedora:30

variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8

before_script:
    - cat /etc/os-release
    - dnf --version
    - dnf --assumeyes group install "C Development Tools and Libraries"
    - dnf --assumeyes install ruby ruby-devel redhat-rpm-config
    - dnf --assumeyes install python
    - ruby --version
    - gem --version
    - gem install bundler
    - bundler install

pages:
    stage: deploy
    script: make build
    artifacts:
        paths:
            - public
    only:
        - master
