image: fedora:30

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /usr/local/share/gems
    - /usr/local/bin
    - /usr/share/gems
    - /root/.gem/ruby
    - /usr/local/share/gems

before_script:
  - cat /etc/os-release
  - dnf --version
  - dnf --assumeyes group install "C Development Tools and Libraries"
  - dnf --assumeyes install ruby ruby-devel redhat-rpm-config
  - gem environment
  - gem install bundler
  - bundler install --jobs $(nproc)

pages:
  stage: deploy
  script: make build
  artifacts:
    paths:
      - public
  only:
    - master
