image: fedora:30

variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8

before_script:
    - cat /etc/os-release
    - dnf --version
    - dnf --assumeyes install make jekyll
    - ruby --version
    - gem --version
    - bundle install

build:
    stage: build
    script: make build
    artifacts:
        paths:
            - public
    only:
        - master

